# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from akash_api.akash.provider.v1beta3 import query_pb2 as akash_dot_provider_dot_v1beta3_dot_query__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in akash/provider/v1beta3/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

class QueryStub(object):
    """Query defines the gRPC querier service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Providers = channel.unary_unary(
                '/akash.provider.v1beta3.Query/Providers',
                request_serializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProvidersRequest.SerializeToString,
                response_deserializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProvidersResponse.FromString,
                _registered_method=True)
        self.Provider = channel.unary_unary(
                '/akash.provider.v1beta3.Query/Provider',
                request_serializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProviderRequest.SerializeToString,
                response_deserializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProviderResponse.FromString,
                _registered_method=True)

class QueryServicer(object):
    """Query defines the gRPC querier service
    """

    def Providers(self, request, context):
        """Providers queries providers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Provider(self, request, context):
        """Provider queries provider details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Providers': grpc.unary_unary_rpc_method_handler(
                    servicer.Providers,
                    request_deserializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProvidersRequest.FromString,
                    response_serializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProvidersResponse.SerializeToString,
            ),
            'Provider': grpc.unary_unary_rpc_method_handler(
                    servicer.Provider,
                    request_deserializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProviderRequest.FromString,
                    response_serializer=akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProviderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akash.provider.v1beta3.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akash.provider.v1beta3.Query', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service
    """

    @staticmethod
    def Providers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.provider.v1beta3.Query/Providers',
            akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProvidersRequest.SerializeToString,
            akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Provider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.provider.v1beta3.Query/Provider',
            akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProviderRequest.SerializeToString,
            akash_dot_provider_dot_v1beta3_dot_query__pb2.QueryProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
