# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from akash_api.akash.audit.v1beta2 import audit_pb2 as akash_dot_audit_dot_v1beta2_dot_audit__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in akash/audit/v1beta2/audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

class MsgStub(object):
    """Msg defines the provider Msg service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignProviderAttributes = channel.unary_unary(
                '/akash.audit.v1beta2.Msg/SignProviderAttributes',
                request_serializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgSignProviderAttributes.SerializeToString,
                response_deserializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgSignProviderAttributesResponse.FromString,
                _registered_method=True)
        self.DeleteProviderAttributes = channel.unary_unary(
                '/akash.audit.v1beta2.Msg/DeleteProviderAttributes',
                request_serializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgDeleteProviderAttributes.SerializeToString,
                response_deserializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgDeleteProviderAttributesResponse.FromString,
                _registered_method=True)

class MsgServicer(object):
    """Msg defines the provider Msg service
    """

    def SignProviderAttributes(self, request, context):
        """SignProviderAttributes defines a method that signs provider attributes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProviderAttributes(self, request, context):
        """DeleteProviderAttributes defines a method that deletes provider attributes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignProviderAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.SignProviderAttributes,
                    request_deserializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgSignProviderAttributes.FromString,
                    response_serializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgSignProviderAttributesResponse.SerializeToString,
            ),
            'DeleteProviderAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProviderAttributes,
                    request_deserializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgDeleteProviderAttributes.FromString,
                    response_serializer=akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgDeleteProviderAttributesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akash.audit.v1beta2.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akash.audit.v1beta2.Msg', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the provider Msg service
    """

    @staticmethod
    def SignProviderAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.audit.v1beta2.Msg/SignProviderAttributes',
            akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgSignProviderAttributes.SerializeToString,
            akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgSignProviderAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProviderAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.audit.v1beta2.Msg/DeleteProviderAttributes',
            akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgDeleteProviderAttributes.SerializeToString,
            akash_dot_audit_dot_v1beta2_dot_audit__pb2.MsgDeleteProviderAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
