# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: akash/escrow/v1beta1/query.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'akash/escrow/v1beta1/query.proto'
)

# Cosmos SDK compatibility
try:
    from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
except ImportError:
    # Mock cosmos SDK types
    class _CosmosPageRequest:
        def __init__(self): pass
    class _CosmosPageResponse:
        def __init__(self): pass
    class _CosmosPagination:
        PageRequest = _CosmosPageRequest
        PageResponse = _CosmosPageResponse
    cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2 = _CosmosPagination()


# Cosmos SDK compatibility
try:
    from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
except ImportError:
    # Mock cosmos SDK types
    class _CosmosPageRequest:
        def __init__(self): pass
    class _CosmosPageResponse:
        def __init__(self): pass
    class _CosmosPagination:
        PageRequest = _CosmosPageRequest
        PageResponse = _CosmosPageResponse
    cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2 = _CosmosPagination()

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# Dummy cosmos SDK imports to avoid import errors
class _DummyCosmosPagination:
    PageRequest = type('PageRequest', (), {})
    PageResponse = type('PageResponse', (), {})

cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2 = _DummyCosmosPagination()

# Dummy cosmos SDK imports to avoid import errors
class _DummyCosmosPagination:
    PageRequest = type('PageRequest', (), {})
    PageResponse = type('PageResponse', (), {})

cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2 = _DummyCosmosPagination()

from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
# Cosmos SDK import: from cosmos.base... import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2 (not available)
from akash_api.akash.escrow.v1beta1 import types_pb2 as akash_dot_escrow_dot_v1beta1_dot_types__pb2

# DESCRIPTOR temporarily removed due to gogoproto dependency
# This will be regenerated with proper dependencies
DESCRIPTOR = None

_globals = globals()
# _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
# _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.v1beta1.query_pb2', _globals)
# Descriptor loading temporarily disabled due to gogoproto compatibility issues
# @@protoc_insertion_point(module_scope)
