# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: akash/deployment/v1beta2/authz.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'akash/deployment/v1beta2/authz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2

# DESCRIPTOR temporarily removed due to gogoproto dependency
# This will be regenerated with proper dependencies
DESCRIPTOR = None

_globals = globals()
# _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
# _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta2.authz_pb2', _globals)
# Descriptor loading temporarily disabled due to gogoproto compatibility issues
# @@protoc_insertion_point(module_scope)
