# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: akash/deployment/v1beta2/groupmsg.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'akash/deployment/v1beta2/groupmsg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from akash_api.akash.deployment.v1beta2 import groupid_pb2 as akash_dot_deployment_dot_v1beta2_dot_groupid__pb2

# DESCRIPTOR temporarily removed due to gogoproto dependency
# This will be regenerated with proper dependencies
DESCRIPTOR = None

_globals = globals()
# _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
# _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta2.groupmsg_pb2', _globals)
# Descriptor loading temporarily disabled due to gogoproto compatibility issues
# @@protoc_insertion_point(module_scope)
