# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from akash_api.akash.deployment.v1beta3 import deploymentmsg_pb2 as akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2
from akash_api.akash.deployment.v1beta3 import groupmsg_pb2 as akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in akash/deployment/v1beta3/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

class MsgStub(object):
    """Msg defines the deployment Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDeployment = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/CreateDeployment',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCreateDeployment.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCreateDeploymentResponse.FromString,
                _registered_method=True)
        self.DepositDeployment = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/DepositDeployment',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgDepositDeployment.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgDepositDeploymentResponse.FromString,
                _registered_method=True)
        self.UpdateDeployment = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/UpdateDeployment',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgUpdateDeployment.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgUpdateDeploymentResponse.FromString,
                _registered_method=True)
        self.CloseDeployment = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/CloseDeployment',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCloseDeployment.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCloseDeploymentResponse.FromString,
                _registered_method=True)
        self.CloseGroup = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/CloseGroup',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgCloseGroup.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgCloseGroupResponse.FromString,
                _registered_method=True)
        self.PauseGroup = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/PauseGroup',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgPauseGroup.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgPauseGroupResponse.FromString,
                _registered_method=True)
        self.StartGroup = channel.unary_unary(
                '/akash.deployment.v1beta3.Msg/StartGroup',
                request_serializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgStartGroup.SerializeToString,
                response_deserializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgStartGroupResponse.FromString,
                _registered_method=True)

class MsgServicer(object):
    """Msg defines the deployment Msg service.
    """

    def CreateDeployment(self, request, context):
        """CreateDeployment defines a method to create new deployment given proper inputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DepositDeployment(self, request, context):
        """DepositDeployment deposits more funds into the deployment account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDeployment(self, request, context):
        """UpdateDeployment defines a method to update a deployment given proper inputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseDeployment(self, request, context):
        """CloseDeployment defines a method to close a deployment given proper inputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseGroup(self, request, context):
        """CloseGroup defines a method to close a group of a deployment given proper inputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseGroup(self, request, context):
        """PauseGroup defines a method to close a group of a deployment given proper inputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGroup(self, request, context):
        """StartGroup defines a method to close a group of a deployment given proper inputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDeployment,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCreateDeployment.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCreateDeploymentResponse.SerializeToString,
            ),
            'DepositDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.DepositDeployment,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgDepositDeployment.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgDepositDeploymentResponse.SerializeToString,
            ),
            'UpdateDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDeployment,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgUpdateDeployment.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgUpdateDeploymentResponse.SerializeToString,
            ),
            'CloseDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseDeployment,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCloseDeployment.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCloseDeploymentResponse.SerializeToString,
            ),
            'CloseGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseGroup,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgCloseGroup.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgCloseGroupResponse.SerializeToString,
            ),
            'PauseGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseGroup,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgPauseGroup.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgPauseGroupResponse.SerializeToString,
            ),
            'StartGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGroup,
                    request_deserializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgStartGroup.FromString,
                    response_serializer=akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgStartGroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akash.deployment.v1beta3.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akash.deployment.v1beta3.Msg', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the deployment Msg service.
    """

    @staticmethod
    def CreateDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/CreateDeployment',
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCreateDeployment.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCreateDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DepositDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/DepositDeployment',
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgDepositDeployment.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgDepositDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/UpdateDeployment',
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgUpdateDeployment.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgUpdateDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/CloseDeployment',
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCloseDeployment.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_deploymentmsg__pb2.MsgCloseDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/CloseGroup',
            akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgCloseGroup.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgCloseGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/PauseGroup',
            akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgPauseGroup.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgPauseGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akash.deployment.v1beta3.Msg/StartGroup',
            akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgStartGroup.SerializeToString,
            akash_dot_deployment_dot_v1beta3_dot_groupmsg__pb2.MsgStartGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
